### ISSUE TITLE
Required prop `location`

### ISSUE THREAD

**Issue by danhanfry** [GordyD/3ree#20]
good, sorry for my English.

Much to react and did not encounter this error.

`Everything works, but I always get the error.
Warning: Failed propType: Required prop `location` was not specified in `RoutingContext`. Check the render method of `ReduxRouterContext``

**Comment by GordyD** [comment]
Thanks for flagging this up. As you state, it does not cause problems, but it is/was an eyesore!

Upon debugging I discovered, when using Chrome, this issue was to do with the browser looking for a favicon, and the server logic being triggered when looking for this file. I have updated the repo to contain a favicon and added a rule in the server to serve this file when requested.

The warning messages in the server console no longer appear.
