### ISSUE TITLE
Add ESlint

### ISSUE THREAD

**Issue by pcanterini** [GordyD/3ree#24]
It might be a good idea to add `ESlint` and `EditorConfig` to help with consistency.

I've recently started using [standardjs](http://standardjs.com/) but it's probably a preference thing based on your code style.

**Comment by GordyD** [comment]
Good call! 

I am on the fence as to which tool (ESLint and Standard) is the best option. On the one hand, seeing standard (thanks for sharing this), it looks great because it is just plug and play - it will not detract from the main focus of this repo. But on the other, as this is a demo/bootstrap repo - it might make sense to use a linting tool that allows for custom rules (although I wouldn't want to get too bogged down in debate so I would probably opt for using [Airbnb's eslint rules](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb)).

Which do you think is best here?

**Comment by pcanterini** [comment]
I vote for consistency too so if you think extending from Airbnb's presets is the closest I'm fine with that. :+1:

**Comment by GordyD** [comment]
Ok. EsLint + Airbnb + EditorConfig sounds good. 

For EditorConfig I think the most important rule is: 

```
[*.js]
indent_style = space
indent_size = 2
```

Anything else?

**Comment by pcanterini** [comment]
LGTM
