### ISSUE TITLE
Slow loading on demo app

### ISSUE THREAD

**Issue by reddhouse** [GordyD/3ree#48]
The content takes a long time to become formatted on the pulse app demo at http://3ree-demo.workshape.io/. Is this because you're hosting it somewhere with a small amount of server "juice" or because I'm seeing the "normal" transition from the server rendered code to the browser rendered code? If the latter, is there a way to have the server code formatted to match the client code so that the user doesn't notice the delay?

**Comment by GordyD** [comment]
Hi @reddhouse,

Thanks for flagging this.

So the issue here is that the CSS is loaded inline with the Javascript payload (it is contained within `bundle.js`) in the version deployed. Because Webpack is not instructed to break out CSS dependencies into separate payloads this means that it is served just like the JS, asynchronously, which explains the page showing the unstyled content initially.

The current version of 3ree addresses this though so I'll need to update the deployed version which I'll do later today, then the CSS will be loaded synchronously and you won't see an unstyled version of the app.

For clarity though this issue is resolved by using the [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin) and updating `webpack.config.js` to optionally use this plugin for bundling CSS when building for non-development environments. See [here](https://github.com/GordyD/3ree/blob/master/webpack.config.js#L35)

**Comment by reddhouse** [comment]
Ah, good to know there is a solution to this. I'll keep an eye out for the refreshed UI on the demo site.

**Comment by GordyD** [comment]
FYI I have just deployed an updated version!
